version: "3.9"
services:
  # collector:
  #   build: ../collector
  #   container_name: collector
  #   devices:
  #     - "/dev/ttyS2:/dev/ttyS2"
  #   ports:
  #     - "127.0.0.1:3001:3000"
  #   # deploy:
  #   #   restart_policy:
  #   #     condition: on-failure
  #   #   resources:
  #   #     limits:
  #   #       memory: 256M
  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
      # - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ../.env

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    ports:
      - 127.0.0.1:9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/prometheus-data:/etc/prometheus
